### ISSUE TITLE
无法应用到项目中

### ISSUE THREAD

**Issue by liuqunqun215** [GGBeng1/Gantt#2]
你好！我把gant.vue引入到项目中，启动项目（npm run dev）后，展示如下，添加分组、右边展示等部分功能都不能用，如果下载工程进行yarn install、yarn run serve是可以的，请问如果使用到 vue的工程中，把gant.vue作为组件使用，谢谢！
<img width="1271" alt="image" src="https://user-images.githubusercontent.com/34654949/66997911-e45de500-f105-11e9-86a9-12a18cbff011.png">

**Comment by GGBeng1** [comment]
你应该使组件没有引入全，你看一下。我的gantt.vue也引入了其他组件
