### ISSUE TITLE
请问位置会跑掉，是哪里改错? 我看 demo 网站也是一样的问题，但是我初始测试时，好像是正确的。

### ISSUE THREAD

**Issue by gexMichael** [GGBeng1/Gantt#33]
请问位置会跑掉，是哪里改错? 我看 demo 网站也是一样的问题，但是我初始测试时，好像是正确的。
![image](https://user-images.githubusercontent.com/22609092/184522060-934ad284-7127-4d42-9ecb-b44b8096788c.png)

![image](https://user-images.githubusercontent.com/22609092/184522097-3e51ec88-6166-40c0-8a9e-759e78f20247.png)

**Comment by gexMichael** [comment]
发现一个奇怪的问题，原先提的 bug，似乎只会发生在星期六、日，其他日子看起来是正常的。

**Comment by Rambo19971009** [comment]
bug的原因是setStoneLine()这个方法里：
```
let height = window.getComputedStyle(
          document.getElementsByClassName("lineBG")[0]
        ).height;
```
获取高度错误导致的，不存在height方法，要用offsetHeight替换
```
        let height = window.getComputedStyle(
          document.getElementsByClassName("lineBG")[0]
        ).offsetHeight;
```

**Comment by rambosystem** [comment]
删掉
`      .today {
        position: relative;
      }`
就可以了

**Comment by gexMichael** [comment]
依建议删除 today，经测试 OK，非常感谢。
另外，我之前在测试时，也试过将 
:style="{
  width: currentDaySize.value + 'px',
  //以下设 height, 会造成周六日的位置错误 2022-09-17 Michael
  //height:
  //	j.weekday == 0 || j.weekday == 6 ? lineBGHeight : '0px'
}"

结果似乎也可行，一并附上参考。
